export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_FRIENDS_STATE_CHANGE = 'USER_FRIENDS_STATE_CHANGE'
export const USER_NOTIFICATIONS_FRIENDREQUESTS_STATE_CHANGE = 'USER_NOTIFICATIONS_FRIENDREQUESTS_STATE_CHANGE'
export const USER_NOTIFICATIONS_OTHER_STATE_CHANGE = 'USER_NOTIFICATIONS_OTHER_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'